---
title: "Reliabilitet NORGAST"
author: "NORGAST"
format:
  html:
    embed-resources: true
---

## Formål
Formålet med prosjektet er ...

## Bakgrunn


## Metode


## Resultater


```{r}
#| echo: false
#| message: false
#| warning: false
library(norgast)
library(dplyr)
library(tidyr)
library(irr)
rm(list = ls())

# 1. Load and clean data
data_reg <- read.csv2(
  "C:/Users/kth200/regdata/norgast/reliabilitet/NORGAST_registration_datadump_20.11.2025.csv") %>%
  filter(STATUS == 1) |>
  filter(!duplicated(paste(CASENUMBER, CREATEDBY))) %>%
  # filter(CREATEDBY != "krlass@ous-hf.no") %>%
  select(where(~ !all(is.na(.)))) %>%
  mutate(across(c(ROBOTASSISTANCE, TATME, RELAPAROTOMY_YES,
                  RELAPAROTOMY_NO, PERCUTANEOUS_DRAINAGE,
                  LEAK_INTERVENTION, BLEED_INTERVENTION,
                  ANGIO_INTERVENTION, LIQUID_DRAINAGE),
                ~replace_na(., -1))) %>%
  mutate(across(c(PREVIOUS_WEIGHT, ADMISSION_WEIGHT, HEIGHT,
                  ALBUMIN, CRP, ANAL_GUARD_DISTANCE, GLASGOW_SCORE,
                  MODIFIED_GLASGOW_SCORE),
                ~replace_na(., -1))) |>
  mutate(ncsp_lowercase = tolower(NCSP)) |>
  dplyr::mutate(
    op_gr = dplyr::case_when(
      substr(ncsp_lowercase,1,3)=="jfh" |
        (substr(ncsp_lowercase,1,3)=="jfb" &
           substr(ncsp_lowercase,4,5) %in% 20:64 ) ~ "Kolon",
      substr(ncsp_lowercase,1,3)=="jgb" ~ "Rektum",
      substr(ncsp_lowercase,1,3)=="jcc" ~ "Øsofagus",
      substr(ncsp_lowercase,1,3)=="jdc" |
        substr(ncsp_lowercase,1,3)=="jdd" ~ "Ventrikkel",
      substr(ncsp_lowercase,1,3)=="jjb" ~ "Lever",
      substr(ncsp_lowercase,1,5) %in% c('jlc10','jlc11') ~ "Distale",
      substr(ncsp_lowercase,1,5) %in% c('jlc00','jlc20','jlc40', 'jlc50', 'jlc96') ~ "Andre pankreas",
      substr(ncsp_lowercase,1,5) %in% c("jlc30","jlc31") ~ "Whipples",
      .default = "Annet"
    ))
data_readm <- read.csv2("C:/Users/kth200/regdata/norgast/reliabilitet/NORGAST_readmission_datadump_20.11.2025.csv") %>%
  filter(STATUS == 1) |>
  merge(data_reg |> select(MCEID, CASENUMBER), by = "MCEID") |>
  filter(!duplicated(paste(CASENUMBER, CREATEDBY))) %>%
  # filter(CREATEDBY != "krlass@ous-hf.no") %>%
  select(where(~ !all(is.na(.)))) %>%
  mutate(across(c(RELAPAROTOMY_YES,
                  RELAPAROTOMY_NO, PERCUTANEOUS_DRAINAGE,
                  LEAK_INTERVENTION, BLEED_INTERVENTION,
                  ANGIO_INTERVENTION, LIQUID_DRAINAGE,
                  PHYSICAL_CONTROL, PHONE_CONTROL, RELAPAROTOMY,
                  INTERVENTION_WITHOUT_ANESTHESIA,
                  SINGLE_ORGAN_FAILURE, MULTI_ORGAN_FAILURE,
                  IN_HOUSE_DEATH),
                ~replace_na(., -1)))

klokebok <- read.csv2("C:/Users/kth200/regdata/norgast/klokebok/NORGAST_klokeboken_02.04.2025.csv")

# 2. Define variables of interest
categorical_vars_reg <- klokebok |> 
  filter(skjemanavn == "Registrering",
         type %in% c("Listevariabel", "Avkrysningsboks")) |>
  select(fysisk_feltnavn) |> unique() |> unlist() |> 
  intersect(names(data_reg)) |>
  c("NCSP", "ICD10", "op_gr")
categorical_vars_readm <- klokebok |> 
  filter(skjemanavn == "Reinnleggelse/oppfølging",
         type %in% c("Listevariabel", "Avkrysningsboks")) |>
  select(fysisk_feltnavn) |> unique() |> unlist() |> 
  intersect(names(data_readm))
numeric_vars_reg <- klokebok |> 
  filter(skjemanavn == "Registrering",
         type == "Tallvariabel") |>
  select(fysisk_feltnavn) |> unique() |> unlist() |> 
  intersect(names(data_reg))
numeric_vars_readm <- klokebok |> 
  filter(skjemanavn == "Reinnleggelse/oppfølging",
         type == "Tallvariabel") |>
  select(fysisk_feltnavn) |> unique() |> unlist() |> 
  intersect(names(data_readm))

# Function to filter columns based on first n rows having no NA
keep_non_na_columns <- function(df, n) {
  # Check each column: are the first n elements all non-NA?
  cols_to_keep <- sapply(df, function(col) all(!is.na(head(col, n))))
  
  # Subset the data frame to keep only those columns
  df_filtered <- df[, cols_to_keep, drop = FALSE]
  
  return(df_filtered)
}

get_mode <- function(v) {
  # Create a frequency table
  freq_table <- table(v)
  
  # Find the name (value) that corresponds to the maximum frequency
  most_frequent_value <- names(freq_table)[which.max(freq_table)]
  
  # Coerce the result back to the original data type of the vector
  # This handles cases where the vector contains numbers
  if (is.numeric(v)) {
    return(as.numeric(most_frequent_value))
  } else {
    return(most_frequent_value)
  }
}

# 3. Function to compute IRR for categorical variables
compute_categorical_IRR <- function(data, var, n) {
  cat("\n=== Inter-Rater Reliability for", var, "===\n")
  
  irr_data <- data %>%
    select(CASENUMBER, CREATEDBY, all_of(var)) %>%
    pivot_wider(names_from = CREATEDBY, values_from = all_of(var)) |>
    mutate(rekkefolge = factor(CASENUMBER, levels = c(1,2,3,5,6,7,4,8))) |>
    arrange(rekkefolge) |> select(-rekkefolge) |>
    keep_non_na_columns(n)
  
  ratings <- irr_data[,-1]
  
  # Drop rows with missing values
  ratings <- na.omit(ratings)
  #
  # Fleiss' or Cohen's Kappa
  if (ncol(ratings) > 2) {
    kappa_result <- kappam.fleiss(ratings)
  } else {
    kappa_result <- kappa2(ratings)
  }
  
  samsvar = agree(ratings)
  
  # Krippendorff's alpha (transpose required)
  kripp_result <- kripp.alpha(t(ratings), method = "nominal")
  
  list(kappa_result = kappa_result,
       kripp_result = kripp_result,
       samsvar = samsvar)
}

samsvar_naiv <- function(data, var) {
  irr_data <- data %>%
    select(CASENUMBER, CREATEDBY, all_of(var)) %>%
    pivot_wider(names_from = CREATEDBY, values_from = all_of(var))
  
  ratings <- irr_data[,-1]
  
  ant_enige <- apply(
    ratings, 1, 
    function(x) {
      mode_dim <- x |> unlist() |> get_mode()
      ant_enige <- sum(x == mode_dim, na.rm = T)
    })
  ikke_na <- apply(
    ratings, 1, 
    function(x) {
      ikke_na <- sum(!is.na(x))
    })
  
  data.frame(var = var,
             ant_enige = sum(ant_enige),
             N = sum(ikke_na))
}


```




```{r}
#| echo: false
#| message: false
#| warning: false
felles <- data_readm |>
  filter(CREATEDBY != "krlass@ous-hf.no") %>%
  select(intersect(names(data_readm), names(data_reg))) |>
  mutate(CASENUMBER = CASENUMBER + 4) |>
  bind_rows(data_reg |>
              filter(CREATEDBY != "krlass@ous-hf.no") %>%
              select(intersect(names(data_readm), names(data_reg))))

alle <- felles |> 
  select(-MCEID, -CENTREID, -USERCOMMENT,
         -TSUPDATED, -UPDATEDBY, -FIRST_TIME_CLOSED,
         -FIRST_TIME_CLOSED_BY, -TSCREATED, -STATUS)

samsvar_alle <- data.frame(
  var = NULL, ant_enige = NULL,  N = NULL)
for (var in setdiff(names(alle), c("CASENUMBER", "CREATEDBY"))) {
  analyse <- samsvar_naiv(alle, var)
  samsvar_alle <- bind_rows(samsvar_alle, analyse)
}
samsvar_alle <- samsvar_alle |> 
  mutate(pst_samsvar = ant_enige/N*100,
         skjema = "begge") |> 
  relocate(skjema)

reg <- data_reg |> 
  filter(CREATEDBY != "krlass@ous-hf.no") %>%
  select(-MCEID, -CENTREID, -USERCOMMENT,
         -TSUPDATED, -UPDATEDBY, -FIRST_TIME_CLOSED,
         -FIRST_TIME_CLOSED_BY, -TSCREATED, -STATUS)

samsvar_reg <- data.frame(
  var = NULL, ant_enige = NULL,  N = NULL)
for (var in setdiff(names(reg), c("CASENUMBER", "CREATEDBY"))) {
  analyse <- samsvar_naiv(reg, var)
  samsvar_reg <- bind_rows(samsvar_reg, analyse)
}
samsvar_reg <- samsvar_reg |> 
  mutate(pst_samsvar = ant_enige/N*100,
         skjema = "basis") |> 
  relocate(skjema)


readm <- data_readm |> 
  filter(CREATEDBY != "krlass@ous-hf.no") %>%
  select(-MCEID, -CENTREID, -USERCOMMENT,
         -TSUPDATED, -UPDATEDBY, -FIRST_TIME_CLOSED,
         -FIRST_TIME_CLOSED_BY, -TSCREATED, -STATUS)

samsvar_readm <- data.frame(
  var = NULL, ant_enige = NULL,  N = NULL)
for (var in setdiff(names(readm), c("CASENUMBER", "CREATEDBY"))) {
  analyse <- samsvar_naiv(readm, var)
  samsvar_readm <- bind_rows(samsvar_readm, analyse)
}
samsvar_readm <- samsvar_readm |> 
  mutate(pst_samsvar = ant_enige/N*100,
         skjema = "oppfølging") |> 
  relocate(skjema)

samsvar_enkel <- bind_rows(
  samsvar_reg, samsvar_readm, samsvar_alle
)

knitr::kable(
  samsvar_enkel,
  caption = "Prosentvis samsvar registreringer i NORGAST", 
  digits = 1,
  align = "l", booktabs = TRUE) |> 
  kableExtra::kable_styling(full_width = FALSE)


```



```{r}
#| echo: false
#| message: false
#| warning: false

samsvar_xtofer <- function(data, var) {
  irr_data <- data %>%
    select(CASENUMBER, CREATEDBY, all_of(var)) %>%
    pivot_wider(names_from = CREATEDBY, values_from = all_of(var)) |> 
    relocate(CASENUMBER, `krlass@ous-hf.no`)
  
  ratings <- irr_data[,-1]
  
  ant_enige <- apply(
    ratings, 1, 
    function(x) {
      mode_dim <- x[1]
      ant_enige <- sum(x[-1] == mode_dim, na.rm = T)
    })
  ikke_na <- apply(
    ratings, 1, 
    function(x) {
      ikke_na <- sum(!is.na(x[-1]))
    })
  
  data.frame(var = var,
             ant_enige = sum(ant_enige),
             N = sum(ikke_na))
}

felles <- data_readm |>
  # filter(CREATEDBY != "krlass@ous-hf.no") %>%
  select(intersect(names(data_readm), names(data_reg))) |>
  mutate(CASENUMBER = CASENUMBER + 4) |>
  bind_rows(data_reg |>
              
              select(intersect(names(data_readm), names(data_reg))))

alle <- felles |> 
  select(-MCEID, -CENTREID, -USERCOMMENT,
         -TSUPDATED, -UPDATEDBY, -FIRST_TIME_CLOSED,
         -FIRST_TIME_CLOSED_BY, -TSCREATED, -STATUS)

samsvar_alle <- data.frame(
  var = NULL, ant_enige = NULL,  N = NULL)
for (var in setdiff(names(alle), c("CASENUMBER", "CREATEDBY"))) {
  analyse <- samsvar_xtofer(alle, var)
  samsvar_alle <- bind_rows(samsvar_alle, analyse)
}
samsvar_alle <- samsvar_alle |> 
  mutate(pst_samsvar = ant_enige/N*100,
         skjema = "begge") |> 
  relocate(skjema)

reg <- data_reg |> 
  # filter(CREATEDBY != "krlass@ous-hf.no") %>%
  select(-MCEID, -CENTREID, -USERCOMMENT,
         -TSUPDATED, -UPDATEDBY, -FIRST_TIME_CLOSED,
         -FIRST_TIME_CLOSED_BY, -TSCREATED, -STATUS)

samsvar_reg <- data.frame(
  var = NULL, ant_enige = NULL,  N = NULL)
for (var in setdiff(names(reg), c("CASENUMBER", "CREATEDBY"))) {
  analyse <- samsvar_xtofer(reg, var)
  samsvar_reg <- bind_rows(samsvar_reg, analyse)
}
samsvar_reg <- samsvar_reg |> 
  mutate(pst_samsvar = ant_enige/N*100,
         skjema = "basis") |> 
  relocate(skjema)


readm <- data_readm |> 
  # filter(CREATEDBY != "krlass@ous-hf.no") %>%
  select(-MCEID, -CENTREID, -USERCOMMENT,
         -TSUPDATED, -UPDATEDBY, -FIRST_TIME_CLOSED,
         -FIRST_TIME_CLOSED_BY, -TSCREATED, -STATUS)

samsvar_readm <- data.frame(
  var = NULL, ant_enige = NULL,  N = NULL)
for (var in setdiff(names(readm), c("CASENUMBER", "CREATEDBY"))) {
  analyse <- samsvar_xtofer(readm, var)
  samsvar_readm <- bind_rows(samsvar_readm, analyse)
}
samsvar_readm <- samsvar_readm |> 
  mutate(pst_samsvar = ant_enige/N*100,
         skjema = "oppfølging") |> 
  relocate(skjema)

samsvar_enkel_xtofer <- bind_rows(
  samsvar_reg, samsvar_readm, samsvar_alle
)

samlet <- merge(samsvar_enkel, 
                samsvar_enkel_xtofer |> select(-N),
                by = c("skjema", "var"),
                suffixes = c("", "_xtofer")) |> 
  relocate(skjema, var, ant_enige, ant_enige_xtofer, N)|> 
  filter(ant_enige != ant_enige_xtofer)


knitr::kable(
  samlet,
  caption = "Prosentvis samsvar med Kristoffer sine registreringer i NORGAST. Viser kun variabler der samsvar med Kristoffer er forskjellig fra samsvar med hyppigst valgte svar (altså forrige tabell).", 
  digits = 1,
  align = "l", booktabs = TRUE) |> 
  kableExtra::kable_styling(full_width = FALSE)


```


```{r}
#| label: reop-norgast
#| echo: false
#| message: false
#| warning: false

reop_npr <- readr::read_csv2(
  "C:/Users/kth200/regdata/norgast/datkvalprosjekt_2026/datafil.csv",
  locale = locale(encoding = "UTF-8"))

replacements <- c(
  "\x9b" = "ø",
  "\x9d" = "Ø",
  "\x86" = "å",
  "\x8f" = "Å",
  "\x91" = "æ",
  "\x92" = "Æ"
)
for (pat in names(replacements)) {
  reop_npr$sykehus_reop <- 
    gsub(pat, replacements[pat], reop_npr$sykehus_reop, 
         useBytes = TRUE)
}

reop_npr <- reop_npr |> 
  mutate(Anestesi = "WDAG" %in% substr(pros, 1, 4),
         .by = c(lopenr, dato_indexoperasjon, prosdato_reop)) |> 
  arrange(lopenr, dato_indexoperasjon, prosdato_reop)


# tmp <- reop_npr |> filter(Anestesi==1) |> 
#   summarise(N = n(), .by = pros) |> 
#   arrange(-N)
# tmp2 <- reop_npr |> filter(Anestesi==1) |> 
#   summarise(N = length(pros), 
#             ncsp = paste0(pros, collapse = ","),
#             .by = c(lopenr, dato_indexoperasjon)) |> 
#   arrange(-N) |> filter(N==1)


# RegData <- norgast::NorgastHentData()$RegData |> 
#   norgast::NorgastPreprosess()
# tmp <- reop_npr |> 
#   mutate(ncsp = RegData$Hovedoperasjon[
#   match(pros, toupper(sub(" .*", "", RegData$Hovedoperasjon)))])

# reop_npr |> 
#   mutate(
#     Anestesi = ifelse(Anestesi, "anestesi", "ikke_anestesi")) |> 
#   count(Anestesi, pros) |> 
#   tidyr::pivot_wider(names_from = Anestesi, 
#                      values_from = n, values_fill = 0) |> 
#   mutate(Total = anestesi + ikke_anestesi) |> 
#   arrange(-Total) |> 
#   janitor::adorn_totals() |> 
#   write.csv2("tab_pros_anestesi.csv", row.names = F,
#              fileEncoding = "Latin1")

# reop_npr |> 
#   count(innmatehast_reop, pros) |> 
#   tidyr::pivot_wider(names_from = innmatehast_reop, 
#                      values_from = n, values_fill = 0) |> 
#   mutate(Total = Planlagt + Akutt) |> 
#   arrange(-Total) |> 
#   janitor::adorn_totals() |> 
#   write.csv2("tab_pros_hgrad.csv", row.names = F,
#              fileEncoding = "Latin1")

# tab_pros <- table(reop_npr |> select(pros, Anestesi), 
#                   useNA = 'ifany') |> 
#   addmargins() |> as.data.frame.matrix()


RegData <- norgast::NorgastHentData()$RegData |> 
  norgast::NorgastPreprosess() |> 
  dplyr::filter(Op_gr %in% c(1:8, 14),
                Aar %in% 2023:2025) |> 
  distinct(PasientID, OpDato, .keep_all = TRUE)

# levert_npr <- read.csv2(
#   "C:/Users/kth200/regdata/norgast/datkvalprosjekt_2026/aktivitetsdata_beriking_norgast.csv") |> 
#   mutate(Aar = as.Date(OperasjonsDato) |> lubridate::year()) |> 
#   dplyr::filter(Aar %in% 2023:2025) |> 
#   distinct(PasientID, OperasjonsDato, .keep_all = TRUE)
# tmp <- reop_npr |> distinct(lopenr, dato_indexoperasjon, 
#                             .keep_all = TRUE)

# forlop <- merge(
#   reop_npr,
#   RegData |> select(PasientID, ForlopsID, 
#                     ncsp_lowercase, OpDato,
#                     ReLapNarkose, OppfReLapNarkose,
#                     Sykehusnavn),
#   by.x = c("lopenr", "dato_indexoperasjon"), 
#   by.y = c("PasientID", "OpDato"), all.x = TRUE
# )  |> 
#   relocate(ncsp_lowercase) 

ncsp_reop <- read.csv2(
  "C:/Users/kth200/regdata/norgast/datkvalprosjekt_2026/2025 ACC4 medkodetekst_gradert_ Handlest KL_avklart.csv"
) |> filter(!is.na(ACCORDION.4)) # fjern ugyldig linje

reop_npr <- merge(reop_npr, ncsp_reop, 
                  by.x = "pros", by.y = "NCSP_code") |> 
  mutate(
    relap_npr_v1 = ACCORDION.4,
    relap_npr_v2 = ACCORDION.4 & 
      !(Informasjon %in% c("Ikke gastro", "Neppe komplikasjon", 
                           "Neppe reoperasjon for komplikasjon"))
  )

relap_npr_forlop = reop_npr |> 
  summarise(
    relap_npr_v1 = sum(relap_npr_v1) > 0,
    relap_npr_v2 = sum(relap_npr_v2) > 0,
    relap_npr_v3 = sum(Anestesi) > 0,
    relap_npr_v4 = sum(relap_npr_v1 | Anestesi) > 0,
    relap_npr_v5 = 1,
    .by = c(lopenr, dato_indexoperasjon)
  ) 

relap_npr_norgast <- merge(
  RegData |> select(PasientID, ForlopsID, 
                    ncsp_lowercase, OpDato,
                    ReLapNarkose, OppfReLapNarkose,
                    Sykehusnavn),
  relap_npr_forlop, 
  by.x = c("PasientID", "OpDato"),
  by.y = c("lopenr", "dato_indexoperasjon"),
  all = T
) |> 
  mutate(
    relap_npr_v1 = ifelse(is.na(relap_npr_v1), 0, relap_npr_v1),
    relap_npr_v2 = ifelse(is.na(relap_npr_v2), 0, relap_npr_v2),
    relap_npr_v3 = ifelse(is.na(relap_npr_v3), 0, relap_npr_v3),
    relap_npr_v4 = ifelse(is.na(relap_npr_v4), 0, relap_npr_v4),
    relap_npr_v5 = ifelse(is.na(relap_npr_v5), 0, relap_npr_v5)
  ) |> 
  summarise(
    relap_norgast = sum(ReLapNarkose),
    
    bare_norgast_v1 = sum(ReLapNarkose & !relap_npr_v1),
    bare_npr_v1 = sum(!ReLapNarkose & relap_npr_v1),
    begge_v1 = sum(ReLapNarkose & relap_npr_v1),
    relap_npr_v1 = sum(relap_npr_v1),
    
    bare_norgast_v2 = sum(ReLapNarkose & !relap_npr_v2),
    bare_npr_v2 = sum(!ReLapNarkose & relap_npr_v2),
    begge_v2 = sum(ReLapNarkose & relap_npr_v2),
    relap_npr_v2 = sum(relap_npr_v2),
    
    bare_norgast_v3 = sum(ReLapNarkose & !relap_npr_v3),
    bare_npr_v3 = sum(!ReLapNarkose & relap_npr_v3),
    begge_v3 = sum(ReLapNarkose & relap_npr_v3),
    relap_npr_v3 = sum(relap_npr_v3),
    
    bare_norgast_v4 = sum(ReLapNarkose & !relap_npr_v4),
    bare_npr_v4 = sum(!ReLapNarkose & relap_npr_v4),
    begge_v4 = sum(ReLapNarkose & relap_npr_v4),
    relap_npr_v4 = sum(relap_npr_v4),
    
    bare_norgast_v5 = sum(ReLapNarkose & !relap_npr_v5),
    bare_npr_v5 = sum(!ReLapNarkose & relap_npr_v5),
    begge_v5 = sum(ReLapNarkose & relap_npr_v5),
    relap_npr_v5 = sum(relap_npr_v5),
    
    N = n(),
    .by = Sykehusnavn
  ) |> janitor::adorn_totals() #|> 
# relocate(Sykehusnavn, relap_norgast, relap_npr_v1,
#          relap_npr_v2, relap_npr_v3, relap_npr_v4, relap_npr_v5)

write.csv2(
  relap_npr_norgast, 
  "C:/Users/kth200/regdata/norgast/datkvalprosjekt_2026/relap_npr_norgast.csv", row.names = F,
  fileEncoding = "Latin1")


#|> 
# summarise(
#   begge_v1 = sum(relap_norgast & relap_npr_v1),
#   begge_v2 = sum(relap_norgast & relap_npr_v2),
#   begge_v3 = sum(relap_norgast & relap_npr_v3),
#   begge_v4 = sum(relap_norgast & relap_npr_v4),
#   relap_norgast = sum(relap_norgast),
#   relap_npr_v1 = sum(relap_npr_v1),
#   relap_npr_v2 = sum(relap_npr_v2),
#   relap_npr_v3 = sum(relap_npr_v3),
#   relap_npr_v4 = sum(relap_npr_v4),
#   N = n(),
#   .by = Sykehusnavn
# ) |> janitor::adorn_totals() |> 
# relocate(Sykehusnavn, relap_norgast, relap_npr_v1, 
#          relap_npr_v2, relap_npr_v3, relap_npr_v4)



# telling1 <- reop_npr |> 
#   dplyr::count(lopenr, dato_indexoperasjon)
# telling2 <- forlop |> 
#   dplyr::count(lopenr, dato_indexoperasjon)
# telling <- merge(telling1, telling2, 
#                  by = c("lopenr", "dato_indexoperasjon")) |> 
#   filter(n.x != n.y)
# tmp <- forlop |> 
#   filter(lopenr == 67913 & dato_indexoperasjon == "2024-05-22") 
# tmp2 <- RegData |> dplyr::count(PasientID, OpDato, ncsp_lowercase) |> 
#   filter(n>1)

```
