testAutoReportFirst:
  synopsis: Test, the first one
  package: rapbase
  type: dispatchment
  fun: .testAutoReport
  params:
    aNum: 1
    aChar: a
    anExp: Sys.Date()
  owner: ttester
  ownerName: Tore Tester
  email:
  - Some One <someone@nowhere.com>
  - Jesus <jesus@sky.com>
  organization: '999999'
  startDate: '1900-01-01'
  terminateDate: '9999-12-31'
  interval: ~
  intervalName: ~
  runDayOfYear:
  - 30
  - 60
testAutoReportSecond:
  synopsis: Test, the second one
  package: rapbase
  type: subscription
  fun: .testAutoReport
  params:
    aNum: 2.0
    aChar: '3.14'
    anExp: sessionInfo()
  owner: ttester
  ownerName: Tore Tester
  email: <someone@nowhere.com>
  organization: '999999'
  startDate: '1900-01-01'
  terminateDate: '9999-12-31'
  interval: ~
  intervalName: ~
  runDayOfYear:
  - 30
  - 60
  - 90
testAutoReportThird:
  synopsis: Test, the second one
  type: bulletin
  package: rapbase
  fun: .testAutoReport
  params:
    aNum: 2.0
    aChar: '3.14'
    anExp: sessionInfo()
    bulletin: yes
  owner: ttester
  ownerName: Tore Tester
  email:
  - <someone@nowhere.com>
  - jesus@sky.com
  organization: '999999'
  startDate: '1900-01-01'
  terminateDate: '9999-12-31'
  interval: ~
  intervalName: ~
  runDayOfYear:
  - 30
  - 60
  - 90
5a0e7e28fd4c641be535a2b292a6b7b2:
  synopsis: Test of auto report
  package: rapbase
  fun: .testAutoReport
  params:
    aNum: '1'
    aChar: someString
    anExp: Sys.Date()
  owner: ttester
  ownerName: Tore Tester
  email: tester@skde.no
  organization: '999999'
  startDate: '1900-01-01'
  terminateDate: '9999-12-31'
  interval: ~
  intervalName: ~
  runDayOfYear: 170.0
  type: subscription
cd467ac14dd848b8798a384a3e51512c:
  synopsis: Test of expired auto report
  package: rapbase
  fun: .testAutoReport
  params:
    aNum: '1'
    aChar: someString
    anExp: Sys.Date()
  owner: ttester
  ownerName: Tore Tester
  email: tester@skde.no
  organization: '999999'
  startDate: '1900-01-01'
  terminateDate: '0000-01-01'
  interval: ~
  intervalName: ~
  runDayOfYear: 171.0
  type: subscription
6dbc4838ca84c92fd255ec6d2ed30dd6:
  synopsis: 'NORGAST: Kvartalsrapport'
  package: norgast
  type: subscription
  fun: abonnement_kvartal_norgast
  params:
    baseName: NorgastKvartalsrapport_abonnement
    reshID: '1'
  owner: test@tester.no
  ownerName: ''
  email: ''
  organization: '1'
  startDate: '2025-03-18'
  terminateDate: '2025-01-18'
  interval: quarter
  intervalName: Kvartalsvis
  runDayOfYear:
  - 77
  - 169
  - 261
  - 352
